# Generated by Django 5.1.7 on 2025-03-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=255, verbose_name='Имя родителя')),
                ('guardian_email', models.EmailField(max_length=254, verbose_name='Email родителя')),
                ('child_name', models.CharField(max_length=255, verbose_name='Имя ребенка')),
                ('child_age', models.PositiveIntegerField(verbose_name='Возраст ребенка')),
                ('message', models.TextField(verbose_name='Сообщение родителя')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приёмы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(upload_to='client_image/', verbose_name='Фотография клиента')),
                ('client_name', models.CharField(max_length=255, verbose_name='ФИО клиента')),
                ('role', models.CharField(max_length=255, verbose_name='Профессия клиента')),
                ('text', models.TextField(verbose_name='Отзыв')),
            ],
        ),
    ]
