# Generated by Django 5.1.7 on 2025-03-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('age', models.CharField(max_length=50, verbose_name='Возраст')),
                ('time', models.CharField(max_length=50, verbose_name='Время')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('role', models.CharField(max_length=255, verbose_name='Роль')),
                ('image', models.ImageField(max_length=255, upload_to='', verbose_name='Фотография')),
            ],
        ),
    ]
